version: "3.8"

services:
  web:
    container_name: web
    restart: on-failure
    image: nginx:latest
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/nginx.conf
      - ./deploy/nginx/backend.conf:/etc/nginx/sites-enabled/backend.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
  frontend:
    container_name: frontend
    restart: on-failure
    ports:
      - "3000:3000"
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - .env
    ports:
      - "8000:8000"
  typesense:
      image: typesense/typesense:27.0
      restart: on-failure
      ports:
        - "8108:8108"
      volumes:
        - ./typesense-data:/data
      command: '--data-dir /data --api-key=magic1337 --enable-cors'  
