version: "3.8"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - .env
    ports:
      - "8000:8000"
  typesense:
      image: typesense/typesense:27.0
      restart: on-failure
      ports:
        - "8108:8108"
      volumes:
        - typesense_data:/data
      command: '--data-dir /data --api-key=magic1337 --enable-cors'  

volumes:
  typesense_data: