version: "3.8"

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - cassandra-data:/var/lib/cassandra
  typesense:
      image: typesense/typesense:27.0
      restart: on-failure
      ports:
        - "8108:8108"
      volumes:
        - typesense_data:/data
      command: '--data-dir /data --api-key=magic1337 --enable-cors'  

volumes:
  typesense_data:
  cassandra-data: